/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Bitmap Converter (ST) for emWin V5.32.                      *
*        Compiled Oct  8 2015, 11:58:22                              *
*                                                                    *
*        (c) 1998 - 2015 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: virag                                                 *
* Dimensions:  88 * 32                                               *
* NumColors:   2                                                     *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

extern GUI_CONST_STORAGE GUI_BITMAP bmvirag;

/*********************************************************************
*
*       Palette
*
*  Description
*    The following are the entries of the palette table.
*    The entries are stored as a 32-bit values of which 24 bits are
*    actually used according to the following bit mask: 0xBBGGRR
*
*    The lower   8 bits represent the Red   component.
*    The middle  8 bits represent the Green component.
*    The highest 8 bits represent the Blue  component.
*/
static GUI_CONST_STORAGE GUI_COLOR _Colorsvirag[] = {
  0x000000, 0xFFFFFF
};

static GUI_CONST_STORAGE GUI_LOGPALETTE _Palvirag = {
  2,  // Number of entries
  0,  // No transparency
  &_Colorsvirag[0]
};

static GUI_CONST_STORAGE unsigned char _acvirag[] = {
  ________, ________, ________, ________, ________, _______X, XXXX____, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, _____XXX, ___XX___, ________, ________, _XXXX___, ________,
  ________, ________, ________, ________, ________, ____XX__, _____XX_, ________, ________, _X__XXXX, XXX_____,
  ________, ________, ______XX, XXXXX___, ________, XXXXXX__, _____XXX, XXX_____, ______X_, _X___XXX, __X__X__,
  ________, ________, ____XXX_, ____XXX_, _______X, X___XX__, _____X__, __XX____, ______XX, XX__XX__, __XXXX__,
  ________, ________, ___XX___, ____XX__, ______XX, _____X__, _____X__, ___XX___, ______XX, XXXXX___, XXX_XX__,
  ________, ________, __XX____, ___XX___, ______X_, _____XX_, _X__XX__, ____X___, ______XX, __XX__XX, X___X___,
  _____XXX, XXXXX___, _XX_____, ___X____, _____XX_, ______X_, _X__X___, ____XX__, _______X, ___XXXX_, ____X___,
  ____XX__, ____XX__, _X______, __X_____, _____X__, ___X__X_, _X_XX__X, ____XX__, _______X, ___XX___, ____X___,
  ___XXX__, ______X_, _X__X___, _X______, _____XX_, ___XX__X, _X_X__XX, ____XX__, _______X, _XX_____, ____X___,
  _____XX_, ______XX, XX__X___, XX______, _____XXX, ____XX_X, XXXX_XX_, __XXXX__, _______X, XX______, ____X___,
  _______X, ___XX__X, _X_X____, X_______, ____X___, XXX__XXX, XXXXXX__, XXX___X_, ______XX, X_______, ____X___,
  ________, X___XXXX, _XXX___X, ________, ___XX___, __XXXXX_, ____XXXX, X_____XX, ______XX, ________, ____XX__,
  ________, _X____XX, _XXX_XX_, ________, ___X____, ____XXX_, ____XX__, _______X, ______X_, ________, _____X__,
  ________, __XXXXXX, _XXXXX__, ________, ___X____, _XXXXX__, _____XXX, XX_____X, _____XX_, ________, _____X__,
  ________, ___XXX_X, XX______, ________, ___X____, _XXXXX__, _____XXX, XX_____X, _____X__, ________, _____X__,
  ________, ________, XX______, ________, ___X____, ____XXX_, ____XXX_, _______X, _____X__, ________, _____XX_,
  ________, ________, X_______, ________, ___XX___, __XXXXX_, ___XX_XX, X_____XX, _____X__, ________, _____XX_,
  ________, ________, X_______, ________, ____X__X, XXX__XXX, XXXXXX__, XXX___X_, _____X__, ________, _____XX_,
  ________, ________, X_______, ________, _____XXX, ____XX_X, XXXX_XX_, ___XXX__, _____XX_, ________, _____XX_,
  ________, ________, X_______, ________, _____X__, ___XX_XX, _X_X__XX, ____XX__, ______X_, ________, _____X__,
  ________, ________, X_______, ________, _____X__, ___X__X_, _X_XX__X, ____XX__, ______XX, ________, ___XX___,
  ________, ________, X_______, ________, _____XX_, ______X_, _X__X___, ____X___, ________, XXXXX_XX, XXXX____,
  ________, ________, X_______, ________, ______X_, _____XX_, _X__XX__, ____X___, ________, XXXXXXXX, X_XX____,
  ________, ________, X_______, ________, ______XX, _____X__, _____X__, ___XX___, ________, X_XXXXXX, X_XX____,
  ________, ________, X_______, ________, _______X, X___XX__, _____X__, __XX____, _______X, XXX__XX_, XXXXX___,
  ________, ________, ________, ________, ________, XXXXXX__, _____XXX, XXX_____, ________, _____XX_, ________,
  ________, ________, ________, ________, ________, _____X__, _____X__, ________, ________, _____XX_, ________,
  ________, ________, ________, ________, ________, ______XX, X_XXX___, ________, ________, _____XX_, ________,
  ________, ________, ________, ________, ________, _______X, XXX_____, ________, ________, _____XX_, ________,
  ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________
};

GUI_CONST_STORAGE GUI_BITMAP bmvirag = {
  88, // xSize
  32, // ySize
  11, // BytesPerLine
  1, // BitsPerPixel
  _acvirag,  // Pointer to picture data (indices)
  &_Palvirag   // Pointer to palette
};

/*************************** End of file ****************************/
